package com.social.socialattributes.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "social")
public class Actions {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String postId;

    @DynamoDBAttribute
    private String postTitle;

    @DynamoDBAttribute
    private String postContent;

    @DynamoDBAttribute
    private String Author;

    @DynamoDBAttribute
    private String dateandTime;

}
